# fly.toml app configuration file generated for express-my-mini-message-board on 2024-02-25T21:07:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'express-my-mini-message-board'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
